daily_etl:
  sources:
    api:
      - "etldbprocess"
    postgresql:
      - aisles
      - clients
      - departments
      - location_areas
      - orders
      - products
      - store_types
      - stores